services:
  app_vba:
    container_name: fe-vba
    restart: unless-stopped
    image: vbagestfe
    networks:
      - default
    ports:
      - "8086:80"
    expose:
      - '8086'
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js

  db_vba:
    image: mysql
    restart: always
    networks:
      - default
    environment:
      MYSQL_DATABASE: 'gestionale_vba'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'MyMysqlP455w0rd!'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3336:3306'
    expose:
      # Opens port 3306 on the container
      - '3336'
      # Where our data will be persisted
    volumes:
      - my-db-vba:/var/lib/mysql

  api_vba:
    container_name: be-vba
    image: vbagestbe
    restart: always
    networks:
      - default
    ports:
      - "5055:5000"
    environment:
      DB_HOST: 'db_vba'
      DB_USER: 'root'
      DB_PASSWORD: 'MyMysqlP455w0rd!'
      DB_NAME: 'gestionale_vba'
      PORT: '5000'
      TOKEN_SECRET: 'ddac02009daea8818b672a059e91b43f410419f1b3a22ddba4b611a70ee3972193026f5b2b9f591fdb659b1121370bce9c6eb2e9d3e982823a11ba64a3be60a4'
      DOMAIN: https://esame.redshome.it
# Names our volume
volumes:
  my-db-vba: