version: '3.9'

services:

  app_vba:
    container_name: fe-vba
    restart: unless-stopped
    image: vbagestfe
    networks:
      - default
    ports:
      - "8086:80"
    expose:
      - '8086'
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js

  db_vba:
    image: amd64/mysql
    restart: always
    networks:
      - default
    environment:
      MYSQL_DATABASE: 'gestionale_vba'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'MyMysqlP455w0rd!'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3336:3306'
    expose:
      # Opens port 3306 on the container
      - '3336'
      # Where our data will be persisted
    volumes:
      - my-db-vba:/var/lib/mysql


  api_vba:
    container_name: be-vba
    image: vbagestbe
    restart: always
    networks:
      - default
    ports:
      - "5055:5000"
    environment:
      DB_HOST: 'db_vba'
      DB_USER: 'root'
      DB_PASSWORD: 'MyMysqlP455w0rd!'
      DB_NAME: 'gestionale_vba'
      PORT: '5000'
      SECRET_KEY: 'chiavesegreta'
# Names our volume
volumes:
  my-db-vba: